<?php /** @link http://stackoverflow.com/a/14769777/1335142 http://stackoverflow.com/a/8896221/1335142 */ ?>
<?php $breadcrumbs = $this->navigation('Zend\Navigation\Admin')->breadcrumbs()->setMinDepth(0); ?>
<?php $items = array_filter(explode($breadcrumbs->getSeparator(), $breadcrumbs->render())); ?>
<?php if ($items) : ?>
    <?php array_unshift($items, sprintf('<a href="%s">%s</a>',
		$this->url('admin/default'),
		$this->translate('Home')
	)); ?>
	<ol class="breadcrumb">
        <?php foreach ($items as $item) : ?>
			<li><?= $item ?></li>
        <?php endforeach; ?>
	</ol>
<?php endif; ?>
