<?php /** @var $flash \Zend\View\Helper\FlashMessenger */ ?>
<?php $flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<ul%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><li>');
$flash->setMessageSeparatorString('</li></ul><ul%s><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><li>');
?>

<?php //\Zend\Debug\Debug::dump(get_class($flash));die(__FILE__); ?>



<?php $messages = ''; ?>
<?php ob_start(); ?>
<?php
    echo nl2br($flash->renderCurrent('error', array('alert', 'alert-dismissible', 'alert-danger'), false));
    echo nl2br($flash->renderCurrent('debug', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->renderCurrent('info', array('alert', 'alert-dismissible', 'alert-info'), false));
    echo nl2br($flash->renderCurrent('warning', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->renderCurrent('default', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->renderCurrent('success', array('alert', 'alert-dismissible', 'alert-success'), false));

    $flash->clearCurrentMessagesFromContainer();

    echo nl2br($flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'), false));
    echo nl2br($flash->render('debug', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->render('info', array('alert', 'alert-dismissible', 'alert-info'), false));
    echo nl2br($flash->render('warning', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'), false));
    echo nl2br($flash->render('success', array('alert', 'alert-dismissible', 'alert-success'), false));

    //echo $this->flashMessenger()->renderCurrent(FlashMessenger::NAMESPACE_ERROR);
    //$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();
    //echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR);
?>
<?php $messages .= ob_get_clean(); ?>

<?php if (trim($messages)) : ?>
    <div class="row-fluid">
        <div class="col-md-12">
            <?= $messages; ?>
        </div>
    </div>
<?php endif; ?>